"use client";

import { FormEvent, useMemo, useState } from "react";
import { GlobalDrawerLayer } from "../../components/GlobalDrawerLayer";
import { createSeedIndicators } from "../clinical-indicator/indicator-store";
import { blankTemplate, canDeleteTemplate, createSeedTemplates, filterDepartments, filterServiceItems, filterTemplates, institutions, moveIndicator, permissionLabel, serviceItems, validateTemplate, type CheckTemplate, type CheckTemplateDraft, type TemplateErrors, type TemplateType } from "./template-store";

const indicatorOptions = createSeedIndicators().filter((item) => item.status === "启用");
const emptyFilters = { keyword: "", type: "", status: "" };

export function CheckTemplateModule({ onNavigateIndicator }: { onNavigateIndicator: () => void }) {
  const [items, setItems] = useState(createSeedTemplates);
  const [filters, setFilters] = useState(emptyFilters);
  const [drawer, setDrawer] = useState<{ mode: "add" | "edit" | "view"; code?: string } | null>(null);
  const [draft, setDraft] = useState<CheckTemplateDraft>(blankTemplate);
  const [initial, setInitial] = useState("");
  const [errors, setErrors] = useState<TemplateErrors>({});
  const [indicatorOpen, setIndicatorOpen] = useState(false);
  const [indicatorQuery, setIndicatorQuery] = useState("");
  const [pendingIndicators, setPendingIndicators] = useState<string[]>([]);
  const [permissionOpen, setPermissionOpen] = useState(false);
  const [departmentQuery, setDepartmentQuery] = useState("");
  const [serviceOpen, setServiceOpen] = useState(false);
  const [serviceQuery, setServiceQuery] = useState("");
  const [discardOpen, setDiscardOpen] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);
  const [toast, setToast] = useState("");
  const filtered = useMemo(() => filterTemplates(items, filters), [items, filters]);
  const visibleIndicators = useMemo(() => { const value = indicatorQuery.trim().toLowerCase(); return indicatorOptions.filter((item) => !value || item.name.toLowerCase().includes(value) || item.code.toLowerCase().includes(value)); }, [indicatorQuery]);
  const visibleDepartments = useMemo(() => filterDepartments(departmentQuery), [departmentQuery]);
  const visibleServices = useMemo(() => filterServiceItems(serviceQuery), [serviceQuery]);
  const readOnly = drawer?.mode === "view";
  const dirty = drawer?.mode !== "view" && initial && JSON.stringify(draft) !== initial;

  function notify(value: string) { setToast(value); window.setTimeout(() => setToast(""), 2200); }
  function openDrawer(mode: "add" | "edit" | "view", code?: string) {
    const next = mode === "add" ? blankTemplate() : structuredClone(items.find((item) => item.code === code)!);
    setDraft(next); setInitial(JSON.stringify(next)); setErrors({}); setDrawer({ mode, code });
  }
  function closeDrawer() { if (dirty) setDiscardOpen(true); else setDrawer(null); }
  function setField<K extends keyof CheckTemplateDraft>(key: K, value: CheckTemplateDraft[K]) { setDraft((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: "" })); }
  function changeType(type: TemplateType) { setDraft((current) => ({ ...current, type, serviceItem: type === "医生查体" ? "" : current.serviceItem })); }
  function submit(event: FormEvent) {
    event.preventDefault(); const nextErrors = validateTemplate(draft, items, drawer?.mode === "edit" ? drawer.code : undefined); setErrors(nextErrors); if (Object.keys(nextErrors).length) return;
    const saved: CheckTemplate = { ...draft, updatedAt: "2026-08-02 16:00" };
    setItems((current) => drawer?.mode === "edit" ? current.map((item) => item.code === drawer.code ? saved : item) : [saved, ...current]);
    notify(drawer?.mode === "edit" ? "模板已更新" : "模板已新增"); setDrawer(null);
  }
  function toggleStatus(code: string) { setItems((current) => current.map((item) => item.code === code ? { ...item, status: item.status === "启用" ? "停用" : "启用" } : item)); notify("模板状态已更新"); }

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">HI</div><div><strong>眼科专科系统</strong><span>Ophthalmology Center</span></div></div><nav aria-label="功能导航"><p className="nav-label">工作台</p><button className="nav-item"><span className="icon">⌂</span><span className="nav-text">专科首页</span></button><button className="nav-item"><span className="icon">▥</span><span className="nav-text">专科人群</span></button><p className="nav-label">基础配置</p><button className="nav-item" onClick={onNavigateIndicator}><span className="icon">◎</span><span className="nav-text">临床指标定义</span></button><button className="nav-item active"><span className="icon">▦</span><span className="nav-text">检查模板配置</span></button><button className="nav-item" disabled><span className="icon">▤</span><span className="nav-text">病历模板配置</span><span className="soon">待建设</span></button><p className="nav-label">业务应用</p><button className="nav-item" disabled><span className="icon">◫</span><span className="nav-text">专科检查报告</span><span className="soon">待建设</span></button></nav><div className="sidebar-foot"><span className="status-dot" /> 原型环境 · V1.0</div></aside>
    <section className="workspace"><header className="topbar"><button className="icon-button">☰</button><div className="topbar-title">Hi-HIS 一体化医生服务</div><div className="topbar-actions"><button className="icon-button">?</button><div className="avatar">俞</div><div className="user"><strong>俞卿青</strong><span>产品管理员</span></div></div></header>
      <main className="content"><div className="breadcrumb">眼科专科管理 <span>/</span> 基础配置 <span>/</span> 检查模板配置</div><section className="page-heading"><div><h1>检查模板配置</h1><p>租户级维护检查模板、服务项目关联、适用科室和报告指标。</p></div><button className="button primary" onClick={() => openDrawer("add")}>＋ 新建检查模板</button></section>
        <section className="card filter-card"><div className="filter-grid template-filters"><label>模板名称 / 编码<input value={filters.keyword} placeholder="请输入模板名称或编码" onChange={(e) => setFilters({ ...filters, keyword: e.target.value })} /></label><label>模板类型<select value={filters.type} onChange={(e) => setFilters({ ...filters, type: e.target.value })}><option value="">全部</option><option>医技检查</option><option>医生查体</option></select></label><label>状态<select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">全部</option><option>启用</option><option>停用</option></select></label></div></section>
        <section className="card table-card"><div className="card-title"><div><h2>模板列表</h2><span>共 {filtered.length} 个模板</span></div><div className="tenant-scope">当前租户：南医眼科集团</div></div><div className="table-wrap">{filtered.length ? <table className="template-table"><thead><tr><th>模板编码</th><th>模板名称</th><th>模板类型</th><th>服务项目</th><th>指标数</th><th>适用科室</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.code}><td><code>{item.code}</code></td><td><strong>{item.name}</strong></td><td><span className="tag type 数值型">{item.type}</span></td><td>{item.serviceItem || "—"}</td><td>{item.indicatorCodes.length}</td><td><span className={item.departmentIds.length ? "permission-specific" : "permission-all"}>{permissionLabel(item.departmentIds)}</span></td><td><span className={`tag status ${item.status}`}>{item.status}</span></td><td>{item.updatedAt}</td><td><div className="row-actions"><button onClick={() => openDrawer("view", item.code)}>查看</button><button onClick={() => openDrawer("edit", item.code)}>编辑</button><button className={item.status === "启用" ? "danger-link" : ""} onClick={() => toggleStatus(item.code)}>{item.status === "启用" ? "停用" : "启用"}</button>{canDeleteTemplate(item) && <button className="danger-link" onClick={() => setDeleteTarget(item.code)}>删除</button>}</div></td></tr>)}</tbody></table> : <div className="empty"><div>⌕</div><h3>未找到符合条件的模板</h3><p>请修改或清空上方筛选条件</p></div>}</div></section>
      </main></section>
    <GlobalDrawerLayer open={Boolean(drawer)} label="检查模板抽屉" onMaskClick={closeDrawer}>{drawer && <aside className="drawer template-drawer" aria-label="检查模板抽屉"><div className="drawer-head"><div><span className="eyebrow">检查模板</span><h2>{drawer.mode === "add" ? "新建检查模板" : drawer.mode === "edit" ? "编辑检查模板" : "检查模板详情"}</h2></div><button className="close" onClick={closeDrawer}>×</button></div><form className="drawer-form" onSubmit={submit}><div className="drawer-body">
      <section className="form-section"><h3><span>1</span>基础信息</h3><div className="form-grid"><Field label="模板名称" required error={errors.name}><input disabled={readOnly} value={draft.name} placeholder="请输入模板名称" onChange={(e) => setField("name", e.target.value)}/></Field><Field label="模板编码" required error={errors.code}><input disabled={readOnly || drawer.mode === "edit"} value={draft.code} placeholder="如 CORNEA_TOPO" onChange={(e) => setField("code", e.target.value.toUpperCase())}/></Field><Field label="模板类型" required><select disabled={readOnly} value={draft.type} onChange={(e) => changeType(e.target.value as TemplateType)}><option>医技检查</option><option>医生查体</option></select></Field>{draft.type === "医技检查" && <Field label="服务项目" required error={errors.serviceItem} hint="用于医生开立医嘱与 PACS 报告回传关联"><button type="button" disabled={readOnly} className="lookup-control" onClick={() => { setServiceQuery(""); setServiceOpen(true); }}>{draft.serviceItem ? <><strong>{draft.serviceItem}</strong><small>{serviceItems.find((item) => item.name === draft.serviceItem)?.code}</small></> : <span>按编码或服务名称查找</span>}<i>⌕</i></button></Field>}<Field label="状态" required><div className="segmented"><button type="button" disabled={readOnly} className={draft.status === "启用" ? "active" : ""} onClick={() => setField("status", "启用")}>启用</button><button type="button" disabled={readOnly} className={draft.status === "停用" ? "active off" : ""} onClick={() => setField("status", "停用")}>停用</button></div></Field><Field wide label="模板说明"><textarea disabled={readOnly} value={draft.description} placeholder="请输入模板使用说明" onChange={(e) => setField("description", e.target.value)}/></Field></div></section>
      <section className="form-section"><h3><span>2</span>科室权限</h3><div className="scope-note"><strong>租户级配置</strong><p>不维护科室时，当前租户下全部机构、全部科室均可使用。</p></div><button type="button" disabled={readOnly} className="select-panel" onClick={() => { setDepartmentQuery(""); setPermissionOpen(true); }}><span><b>{permissionLabel(draft.departmentIds)}</b><small>{draft.departmentIds.length ? "点击调整机构与科室" : "默认全租户可用"}</small></span><i>›</i></button></section>
      <section className="form-section"><h3><span>3</span>指标配置</h3><div className="section-toolbar"><span>已选择 {draft.indicatorCodes.length} 个指标，可调整展示顺序</span><button type="button" disabled={readOnly} className="button" onClick={() => { setPendingIndicators([...draft.indicatorCodes]); setIndicatorQuery(""); setIndicatorOpen(true); }}>＋ 选择指标</button></div>{errors.indicatorCodes && <div className="error">{errors.indicatorCodes}</div>}<div className="selected-indicators">{draft.indicatorCodes.length ? draft.indicatorCodes.map((code, index) => { const item = indicatorOptions.find((option) => option.code === code); return <div key={code}><b>{index + 1}</b><strong>{item?.name}</strong><code>{code}</code><span>{item?.type}</span><span>{item?.eyeRule.join(" / ")}</span>{!readOnly && <span className="sort-actions"><button type="button" disabled={index === 0} onClick={() => setField("indicatorCodes", moveIndicator(draft.indicatorCodes, index, -1))}>↑</button><button type="button" disabled={index === draft.indicatorCodes.length - 1} onClick={() => setField("indicatorCodes", moveIndicator(draft.indicatorCodes, index, 1))}>↓</button><button type="button" onClick={() => setField("indicatorCodes", draft.indicatorCodes.filter((value) => value !== code))}>移除</button></span>}</div>; }) : <div className="mini-empty">尚未选择指标</div>}</div></section>
    </div><div className="drawer-foot">{readOnly ? <button className="button primary" type="button" onClick={() => setDrawer(null)}>关闭</button> : <><button className="button" type="button" onClick={closeDrawer}>取消</button><button className="button primary" type="submit">保存</button></>}</div></form></aside>}</GlobalDrawerLayer>
    {permissionOpen && <Modal title="选择适用科室" onClose={() => setPermissionOpen(false)} footer={<><span className="selected-count">已选 {draft.departmentIds.length} 个科室</span><button className="button" onClick={() => { setField("departmentIds", []); setPermissionOpen(false); }}>全部科室</button><button className="button primary" onClick={() => setPermissionOpen(false)}>确认选择</button></>}><input className="picker-search" value={departmentQuery} placeholder="搜索机构、科室名称或科室编码" onChange={(e) => setDepartmentQuery(e.target.value)}/><div className="org-tree">{institutions.map((org) => { const deps = visibleDepartments.filter((item) => item.institutionId === org.id); return deps.length ? <section key={org.id}><h4>{org.name}</h4>{deps.map((dep) => <label key={dep.id}><input type="checkbox" checked={draft.departmentIds.includes(dep.id)} onChange={() => setField("departmentIds", draft.departmentIds.includes(dep.id) ? draft.departmentIds.filter((id) => id !== dep.id) : [...draft.departmentIds, dep.id])}/><span><b>{dep.name}</b><small>{dep.id}</small></span></label>)}</section> : null; })}</div></Modal>}
    {indicatorOpen && <Modal title="选择指标" onClose={() => setIndicatorOpen(false)} footer={<><span className="selected-count">已选 {pendingIndicators.filter((code) => !draft.indicatorCodes.includes(code)).length} 项</span><button className="button" onClick={() => setIndicatorOpen(false)}>取消</button><button className="button primary" onClick={() => { setField("indicatorCodes", pendingIndicators); setIndicatorOpen(false); }}>添加选中</button></>}><input className="picker-search" value={indicatorQuery} placeholder="搜索指标名称 / 编码" onChange={(e) => setIndicatorQuery(e.target.value)}/><div className="indicator-list"><div className="indicator-list-head"><span/><span>指标名称 / 编码</span><span>数据类型</span><span>单位</span><span>眼别</span><span>来源</span><span>状态</span></div>{visibleIndicators.map((item) => { const selected = pendingIndicators.includes(item.code); const added = draft.indicatorCodes.includes(item.code); return <label key={item.code} className={selected ? "selected" : ""}><input type="checkbox" checked={selected} onChange={() => setPendingIndicators(selected ? pendingIndicators.filter((code) => code !== item.code) : [...pendingIndicators, item.code])}/><span><strong>{item.name}</strong><small>{item.code}</small></span><span>{item.type}</span><span>{item.unit || "—"}</span><span>{item.eyeRule.join("/")}</span><span>{item.source}</span><span className={added ? "already" : ""}>{added ? "已添加" : "可选择"}</span></label>; })}</div></Modal>}
    {serviceOpen && <Modal title="选择服务项目" onClose={() => setServiceOpen(false)} footer={<button className="button" onClick={() => setServiceOpen(false)}>取消</button>}><input autoFocus className="picker-search" value={serviceQuery} placeholder="按服务项目编码或名称模糊查找" onChange={(e) => setServiceQuery(e.target.value)}/><div className="service-list">{visibleServices.map((item) => { const linked = items.find((template) => template.type === "医技检查" && template.serviceItem === item.name && template.code !== (drawer?.mode === "edit" ? drawer.code : undefined)); return <button key={item.code} disabled={Boolean(linked)} title={linked ? `已关联检查模板“${linked.name}”` : ""} onClick={() => { setField("serviceItem", item.name); setServiceOpen(false); }}><span><strong>{item.name}</strong><small>{item.code}</small></span><i>{linked ? `已关联：${linked.name}` : "选择"}</i></button>; })}</div></Modal>}
    {deleteTarget && <Modal title="确认删除检查模板？" onClose={() => setDeleteTarget(null)} footer={<><button className="button" onClick={() => setDeleteTarget(null)}>取消</button><button className="button danger" onClick={() => { setItems((current) => current.filter((item) => item.code !== deleteTarget)); setDeleteTarget(null); notify("检查模板已删除"); }}>确认删除</button></>}><p className="modal-message">该模板未被治疗方案或业务引用，且没有历史检查实例，删除后不可恢复。</p></Modal>}
    {discardOpen && <Modal title="放弃未保存的修改？" onClose={() => setDiscardOpen(false)} footer={<><button className="button" onClick={() => setDiscardOpen(false)}>继续编辑</button><button className="button danger" onClick={() => { setDiscardOpen(false); setDrawer(null); }}>放弃修改</button></>}><p className="modal-message">当前模板尚未保存，关闭后本次修改将丢失。</p></Modal>}
    {toast && <div className="toast"><span>✓</span>{toast}</div>}
  </div>;
}

function Field({ label, required, error, hint, wide, children }: { label: string; required?: boolean; error?: string; hint?: string; wide?: boolean; children: React.ReactNode }) { return <label className={`field ${wide ? "wide" : ""}`}><span className="field-label">{required && <b>*</b>}{label}</span>{children}{hint && <span className="hint">{hint}</span>}{error && <span className="error">{error}</span>}</label>; }
function Modal({ title, onClose, footer, children }: { title: string; onClose: () => void; footer: React.ReactNode; children: React.ReactNode }) { return <><div className="overlay dialog-layer"/><div className="picker-modal" role="dialog"><div className="picker-head"><h3>{title}</h3><button onClick={onClose}>×</button></div><div className="picker-body">{children}</div><div className="picker-foot">{footer}</div></div></>; }
