"use client";
import { useMemo, useState, type ReactNode } from "react";
import { GlobalDrawerLayer } from "../../components/GlobalDrawerLayer";
import { indicatorDefinition, projectCatalog, projectReports, visits, visibleReports, type IndicatorValue, type Report, type ReportDocument } from "./report-store";

const allProjects=projectCatalog.map(p=>p.name);
const sourceGroups=[{source:"医生查体",title:"本次医生查体",note:"加载本次就诊医生在病历中录入的查体模板"},{source:"护士采集",title:"当日护士采集",note:"按患者、机构和就诊日期加载全部记录，护士采集只读"},{source:"医技检查",title:"本次就诊医嘱",note:"展示本次就诊已开立的全部检查，包含未出报告"},{source:"医生补录",title:"医生补录",note:"基于原始报告形成的结构化补录记录"}] as const;

export function ExamReportModule({embedded=false,onClose}:{embedded?:boolean;onClose?:()=>void}){
 const [view,setView]=useState<"visit"|"project">("visit"),[visit,setVisit]=useState(visits[0].time),[status,setStatus]=useState(""),[selectedProjects,setSelectedProjects]=useState(allProjects),[search,setSearch]=useState(""),[original,setOriginal]=useState<Report|null>(null),[editing,setEditing]=useState<Report|null>(null),[trendProject,setTrendProject]=useState<string|null>(null),[toast,setToast]=useState("");
 const rows=useMemo(()=>visibleReports([],status),[status]); const filteredProjects=projectCatalog.filter(p=>`${p.name}${p.code}`.toLowerCase().includes(search.toLowerCase()));
 const notify=(t:string)=>{setToast(t);window.setTimeout(()=>setToast(""),2200)}; const toggleProject=(name:string)=>setSelectedProjects(x=>x.includes(name)?x.filter(n=>n!==name):[...x,name]);
 return <div className={`er-page ${embedded?"embedded":""}`}>
  {!embedded&&<div className="er-breadcrumb">眼科专科管理 <span>/</span> 检查报告查询</div>}
  <div className="er-title"><div><h1>{embedded?"当前患者检查报告":"检查报告查询"}</h1><p>按就诊记录查看结果，或按检查项目对比历次指标。</p></div><div className="er-patient"><span>当前接诊患者</span><strong>吴四</strong><span>男　14岁　V0000009340</span><small>随医生站患者自动切换</small></div></div>
  <section className="er-filter embedded-filter"><label>{view==="visit"?"就诊时间":"报告时间"}<input defaultValue="2025-08-04 至 2026-08-04"/></label><label>执行科室<select><option>全部</option><option>眼视光中心</option></select></label><div className="er-status-field"><span>报告状态</span><div className="er-status-options">{[["","全部"],["已出报告","已出报告"],["未出报告","未出报告"]].map(([v,n])=><button key={n} className={status===v?"active":""} onClick={()=>setStatus(v)}>{n}</button>)}</div></div><button className="er-btn primary" onClick={()=>notify("查询条件已生效")}>查询</button><button className="er-btn" onClick={()=>setStatus("")}>重置</button></section>
  <div className="er-tabs"><button className={view==="visit"?"active":""} onClick={()=>setView("visit")}>按就诊记录</button><button className={view==="project"?"active":""} onClick={()=>setView("project")}>按检查项目</button></div>
  {view==="visit"?<div className="er-visit-layout"><section className="er-visits"><header><b>就诊记录</b><small>按就诊时间倒序</small></header>{visits.map(v=><button key={v.time} className={visit===v.time?"active":""} onClick={()=>setVisit(v.time)}><strong>{v.time}</strong><span>{v.department} · {v.doctor}</span><small className="er-visit-diagnosis" title={v.diagnosis}>诊断：{v.diagnosis}</small></button>)}</section><section className="er-report-list"><header><div><h2>{visit.slice(0,10)} 检查结果</h2><p>按业务来源加载，结构化内容由检查模板定义</p></div><span className="er-visit-chip">{visits.find(v=>v.time===visit)?.department} · {visits.find(v=>v.time===visit)?.doctor}</span></header>{sourceGroups.map(g=>{const items=rows.filter(r=>r.visit===visit&&r.source===g.source).sort((a,b)=>(b.reportTime??"").localeCompare(a.reportTime??""));return items.length?<section className="er-source-group" key={g.source}><div className="er-source-title"><div><b>{g.title}</b><span>{g.note}</span></div><em>{items.length} 条</em></div>{g.source==="护士采集"?<NursingCollectionTable items={items}/>:items.map(r=><ReportCard key={r.id} item={r} onOriginal={()=>setOriginal(r)} onEdit={()=>setEditing(r)}/>)}</section>:null})}</section></div>:
  <section className="er-project-layout"><aside className="er-project-side"><header><div><b>检查项目</b><small>默认全选，点击立即生效</small></div></header><div className="er-project-search"><span>⌕</span><input placeholder="搜索检查项目名称或编码" value={search} onChange={e=>setSearch(e.target.value)}/></div><label className="er-flat-check all"><input type="checkbox" checked={selectedProjects.length===allProjects.length} onChange={()=>setSelectedProjects(selectedProjects.length===allProjects.length?[]:allProjects)}/><i/><span><b>全部</b><small>已选检查项目 {selectedProjects.length} 项</small></span></label>{filteredProjects.map(p=><label className="er-flat-check" key={p.code}><input type="checkbox" checked={selectedProjects.includes(p.name)} onChange={()=>toggleProject(p.name)}/><i/><span><b>{p.name}</b><small>{p.code}</small></span></label>)}</aside><main className="er-project-main">{selectedProjects.length?selectedProjects.map(name=><ProjectSection key={name} project={name} onOriginal={setOriginal} onEdit={setEditing} onTrend={()=>setTrendProject(name)}/>):<div className="er-empty-card">请选择至少一个检查项目</div>}</main></section>}
  {original&&<OriginalReportModal item={original} onClose={()=>setOriginal(null)}/>} {editing&&<EditReport item={editing} onClose={()=>setEditing(null)} onSave={()=>{setEditing(null);notify("已保存修订版本")}}/>} {trendProject&&<TrendModal project={trendProject} onClose={()=>setTrendProject(null)}/>} {embedded&&<button className="er-panel-close" onClick={onClose}>关闭报告</button>}{toast&&<div className="toast"><span>✓</span>{toast}</div>}
 </div>;
}

function ReportCard({item,onOriginal,onEdit}:{item:Report;onOriginal:()=>void;onEdit:()=>void}){const editable=item.status==="已出报告"&&item.source!=="护士采集";return <article className="er-report-card"><header><div><b>{item.project}</b><span className={`er-status ${item.status}`}>{item.status}</span><em>{item.source}</em>{item.documents&&item.documents.length>1&&<span className="er-file-count">{item.documents.length}份报告</span>}</div><div className="er-card-header-right"><div className="er-card-meta-inline"><span>执行科室：<b>{item.department}</b></span><span>{item.source==="护士采集"?"采集人":"报告/录入人"}：<b>{item.reporter??"—"}</b></span><span>{item.source==="护士采集"?"采集时间":"报告/录入时间"}：<b>{item.reportTime??"—"}</b></span>{item.revisedBy&&<span>补录/修订：<b>{item.revisedBy} · {item.revisedTime}</b></span>}</div><div className="er-card-actions">{item.source==="护士采集"?<span className="er-readonly">只读</span>:<button onClick={onEdit} disabled={!editable}>编辑</button>}{item.documents?.length?<button onClick={onOriginal}>查看原始报告</button>:null}</div></div></header><div className="er-summary"><small>模板展示结果</small>{item.summary.map(s=><p key={s}>{s}</p>)}</div></article>}

function NursingCollectionTable({items}:{items:Report[]}){return <div className="er-nursing-table"><div className="er-nursing-head"><span>指标</span><span>指标结果</span><span>参考范围</span><span>采集人</span><span>采集时间</span></div>{items.map(item=><div className="er-nursing-row" key={item.id}><b>{item.project}</b><div>{item.summary.map(line=><span key={line}>{line}</span>)}</div><span>{Array.from(new Set((item.values??[]).map(value=>indicatorDefinition(value).referenceRange||"—"))).join("；")}</span><span>{item.reporter}</span><time>{item.reportTime}</time></div>)}</div>}

function ProjectSection({project,onOriginal,onEdit,onTrend}:{project:string;onOriginal:(r:Report)=>void;onEdit:(r:Report)=>void;onTrend:()=>void}){const list=projectReports(project);const code=projectCatalog.find(p=>p.name===project)?.code;const columns=Array.from(new Map(list.flatMap(r=>r.values??[]).map(v=>[`${v.eye}-${v.name}-${v.unit??""}`,v])).values());return <section className="er-project-section" id={`project-${code}`}><header><div><h2>{project}</h2><p>每项指标直接成列，一次检查占一行，按报告时间倒序</p></div><button className="er-btn" onClick={onTrend}>趋势分析</button></header>{list.length?<div className="er-history-table"><table><thead><tr><th className="fixed-time">报告时间</th><th className="fixed-person">报告人</th>{columns.map(v=>{const meta=indicatorDefinition(v);return <th key={`${v.eye}-${v.name}-${v.unit}`}><b>{v.eye}</b> {v.name}<small>{v.unit||"无单位"} · 参考 {meta.referenceRange||"—"}</small></th>})}<th>结果来源</th><th>补录/修订</th><th className="fixed-action">操作</th></tr></thead><tbody>{list.map(r=><tr key={r.id}><td className="fixed-time">{r.reportTime}</td><td className="fixed-person">{r.reporter}</td>{columns.map(c=>{const v=r.values?.find(x=>x.name===c.name&&x.eye===c.eye&&x.unit===c.unit);return <td key={`${c.eye}-${c.name}-${c.unit}`} className={v?.abnormal?"abnormal":""}>{v?`${v.value}${v.unit||""}`:"—"}</td>})}<td><em>{r.source}</em></td><td>{r.revisedBy?`${r.revisedBy} · ${r.revisedTime}`:"—"}</td><td className="fixed-action">{r.source!=="护士采集"&&<button onClick={()=>onEdit(r)}>编辑</button>}{r.documents?.length?<button onClick={()=>onOriginal(r)}>查看原始报告</button>:<span>只读</span>}</td></tr>)}</tbody></table></div>:<div className="er-empty">暂无已出具的检查结果</div>}</section>}

function OriginalReportModal({item,onClose}:{item:Report;onClose:()=>void}){const docs=item.documents??[];const [activeId,setActiveId]=useState(docs[0]?.id);const active=docs.find(d=>d.id===activeId)??docs[0];return <><div className="overlay"/><div className="er-pdf-modal"><header><div><span className="eyebrow">原始报告预览</span><h2>{item.project}</h2></div><div className="er-report-meta">执行科室：{item.department}　报告人：{active?.reporter}　报告时间：{active?.reportTime}</div><button className="close" onClick={onClose}>×</button></header><div className="er-document-tabs"><b>报告文件</b>{docs.map((d:ReportDocument)=><button key={d.id} className={d.id===active?.id?"active":""} onClick={()=>setActiveId(d.id)}>{d.eye} · {d.label}<small>{d.reportTime.slice(11)}</small></button>)}</div><div className="er-pdf-viewer">{active&&<iframe title={`${item.project}-${active.label}`} src={active.url}/>}</div><footer><span>医院提供的原始 PDF 样例 · 只读预览</span><a className="er-btn" href={active?.url} target="_blank">新窗口打开</a><button className="er-btn primary" onClick={onClose}>关闭</button></footer></div></>}

function EditReport({item,onClose,onSave}:{item:Report;onClose:()=>void;onSave:()=>void}){const [values,setValues]=useState(item.values??[]);function update(index:number,value:string){setValues(current=>current.map((itemValue,itemIndex)=>itemIndex===index?{...itemValue,value}:itemValue))}return <GlobalDrawerLayer open label="结构化结果修订" onMaskClick={onClose}><aside className="drawer er-drawer"><header className="drawer-head"><div><span className="eyebrow">眼科检查组件 · 结构化结果修订</span><h2>{item.project}</h2></div><button className="close" onClick={onClose}>×</button></header><div className="drawer-body"><div className="er-detail-meta"><b>按指标定义的数据类型录入</b><small>参考范围、单位及枚举值来自临床指标定义；保存生成修订版本，不覆盖接口原值。</small></div><div className="er-component-entry"><div className="er-component-head"><span>眼别</span><span>检查指标</span><span>结果录入</span><span>参考范围</span></div>{values.map((value,index)=><IndicatorEditor key={`${value.eye}-${value.name}-${index}`} value={value} onChange={next=>update(index,next)}/>)}</div><label className="er-textarea">修订原因<textarea placeholder="请输入修订原因"/></label></div><footer className="drawer-foot"><button className="er-btn" onClick={onClose}>取消</button><button className="er-btn primary" onClick={onSave}>保存修订</button></footer></aside></GlobalDrawerLayer>}

function IndicatorEditor({value,onChange}:{value:IndicatorValue;onChange:(value:string)=>void}){const meta=indicatorDefinition(value);let control:ReactNode;if(meta.type==="枚举型")control=<select aria-label={`${value.eye}-${value.name}`} value={value.value} onChange={event=>onChange(event.target.value)}>{(meta.options??[]).map(option=><option key={option}>{option}</option>)}</select>;else if(meta.type==="多选枚举")control=<div className="er-multi-enum">{(meta.options??[]).map(option=><label key={option}><input type="checkbox" checked={value.value.split("、").includes(option)} onChange={()=>{const current=value.value?value.value.split("、"):[];onChange(current.includes(option)?current.filter(item=>item!==option).join("、"):[...current,option].join("、"))}}/>{option}</label>)}</div>;else if(meta.type==="布尔型")control=<div className="er-boolean-entry"><button type="button" className={value.value===(meta.trueLabel??"是")?"active":""} onClick={()=>onChange(meta.trueLabel??"是")}>{meta.trueLabel??"是"}</button><button type="button" className={value.value===(meta.falseLabel??"否")?"active":""} onClick={()=>onChange(meta.falseLabel??"否")}>{meta.falseLabel??"否"}</button></div>;else control=<div className="er-value-input"><input aria-label={`${value.eye}-${value.name}`} type={meta.type==="数值型"?"number":"text"} value={value.value} onChange={event=>onChange(event.target.value)}/>{value.unit&&<i>{value.unit}</i>}</div>;return <div className="er-component-row"><b>{value.eye}</b><span><strong>{value.name}</strong><small>{meta.type}</small></span><div>{control}</div><small>{meta.referenceRange||"—"}</small></div>}

const trendColors=["#2469F2","#22A046","#E5710B","#8B5CF6","#E03134","#0891B2","#C026D3","#4D7C0F"];
function TrendModal({project,onClose}:{project:string;onClose:()=>void}){const list=projectReports(project);const numeric=Array.from(new Map(list.flatMap(r=>(r.values??[]).filter(v=>Number.isFinite(Number(v.value)))).map(v=>[`${v.eye}-${v.name}-${v.unit}`,v])).values());const [selected,setSelected]=useState(numeric.map(v=>`${v.eye}-${v.name}-${v.unit}`));const units=Array.from(new Set(numeric.filter(v=>selected.includes(`${v.eye}-${v.name}-${v.unit}`)).map(v=>v.unit||"无单位")));return <><div className="overlay"/><div className="er-trend-modal"><header><div><h2>{project}趋势分析</h2><p>默认展示全部数值型指标；图例、数据点和数值一一对应</p></div><button className="close" onClick={onClose}>×</button></header><div className="er-trend-tools"><span>指标选择</span><button onClick={()=>setSelected(numeric.map(v=>`${v.eye}-${v.name}-${v.unit}`))}>全选</button><button onClick={()=>setSelected([])}>清空</button></div><div className="er-series-options">{numeric.map((v,index)=>{const key=`${v.eye}-${v.name}-${v.unit}`;return <label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={()=>setSelected(x=>x.includes(key)?x.filter(k=>k!==key):[...x,key])}/><i/><span className="er-legend-dot" style={{background:trendColors[index%trendColors.length]}}/><span>{v.eye} {v.name}</span><small>{v.unit}</small></label>})}</div><div className="er-trend-scroll">{units.length?units.map(unit=><TrendUnitChart key={unit} unit={unit} list={list} numeric={numeric} selected={selected}/>):<div className="er-empty">请选择需要展示的指标</div>}</div><footer>{selected.length} 条指标序列 · 点击数据点可定位对应检查记录</footer></div></>}

function TrendUnitChart({unit,list,numeric,selected}:{unit:string;list:Report[];numeric:{name:string;eye:string;unit?:string}[];selected:string[]}){const ordered=[...list].reverse();const series=numeric.map((v,index)=>({v,index,key:`${v.eye}-${v.name}-${v.unit}`})).filter(s=>selected.includes(s.key)&&(s.v.unit||"无单位")===unit);const allValues=series.flatMap(s=>ordered.map(r=>Number(r.values?.find(v=>v.name===s.v.name&&v.eye===s.v.eye&&v.unit===s.v.unit)?.value)).filter(Number.isFinite));const rawMin=Math.min(...allValues),rawMax=Math.max(...allValues),padding=Math.max((rawMax-rawMin)*.18,.2),min=rawMin-padding,max=rawMax+padding;const x=(i:number)=>70+(ordered.length<2?0:i*620/(ordered.length-1));const y=(value:number)=>180-(value-min)*140/(max-min||1);return <section className="er-trend-unit"><div className="er-trend-unit-head"><h3>单位：{unit} · {series.length}条曲线</h3><div>{series.map(s=><span key={s.key}><i style={{background:trendColors[s.index%trendColors.length]}}/>{s.v.eye} {s.v.name}</span>)}</div></div><svg className="er-real-chart" viewBox="0 0 760 230" role="img" aria-label={`${unit}趋势图`}><line x1="70" y1="40" x2="70" y2="180"/><line x1="70" y1="180" x2="720" y2="180"/>{[0,1,2,3].map(i=>{const value=max-(max-min)*i/3,yy=40+140*i/3;return <g key={i}><line className="grid" x1="70" y1={yy} x2="720" y2={yy}/><text x="62" y={yy+4} textAnchor="end">{value.toFixed(unit==="mmHg"?0:2)}</text></g>})}{series.map(s=>{const color=trendColors[s.index%trendColors.length];const points=ordered.map((r,i)=>{const found=r.values?.find(v=>v.name===s.v.name&&v.eye===s.v.eye&&v.unit===s.v.unit);return found?{x:x(i),y:y(Number(found.value)),value:found.value,date:(r.reportTime??r.visit).slice(0,10),reporter:r.reporter}:null}).filter(Boolean) as {x:number;y:number;value:string;date:string;reporter?:string}[];return <g key={s.key} data-series-key={s.key}><polyline points={points.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={color} strokeWidth="2.5"/>{points.map((p,i)=><g key={p.date+i}><circle cx={p.x} cy={p.y} r="4.5" fill="#fff" stroke={color} strokeWidth="2"><title>{s.v.eye} {s.v.name}：{p.value}{unit}；{p.date}；{p.reporter}</title></circle><text className="point-value" x={p.x} y={p.y-8} textAnchor="middle" fill={color}>{p.value}</text></g>)}</g>})}{ordered.map((r,i)=><text key={r.id} className="x-label" x={x(i)} y="204" textAnchor="middle">{(r.reportTime??r.visit).slice(5,10)}</text>)}</svg><div className="er-trend-data"><table><thead><tr><th>报告/采集时间</th><th>报告/采集人</th>{series.map(s=><th key={s.key}>{s.v.eye} {s.v.name}</th>)}</tr></thead><tbody>{[...ordered].reverse().map(r=><tr key={r.id}><td>{r.reportTime??r.visit}</td><td>{r.reporter}</td>{series.map(s=>{const v=r.values?.find(v=>v.name===s.v.name&&v.eye===s.v.eye&&v.unit===s.v.unit);return <td key={s.key}>{v?`${v.value}${v.unit}`:"—"}</td>})}</tr>)}</tbody></table></div></section>}
